### ISSUE TITLE
DBM Half-Bar Skin broken since last update.

### ISSUE THREAD

**Issue by carlschoeneich** [Azilroka/AddOnSkins#10]
After I downloaded the last update for AddonSkins my DBM with the Half-Bar Skin seems to be broken.
When I just log in and don't change anything in the settings the bars appear to have a very small height of 1px. Then I can go to the settings and set the height to the minimum of 10 but that seems to be bigger than my bars were before the update.
But no matter what the settings in DMB will be overridden whenever I log in the next time.

**Comment by Azilroka** [comment]
You have to use the alpha version of DBM thats what the new version is setup for.

**Comment by carlschoeneich** [comment]
I actually tried it now with the alpha version and it still resets the height of the bars every time I log in and it only happens when I have the half-bars enabled.
