### ISSUE TITLE
unpack(AS.BorderColor) is always using the default/wrong color.

### ISSUE THREAD

**Issue by aLanaMaunz** [Azilroka/AddOnSkins#11]
https://github.com/Azilroka/AddOnSkins/blob/642de89bc9059b4d267fec1b98a04a1ea3f0ace2/AddOnSkins/Core/Core.lua#L255
Hello. Somehow all unpack(AS.BorderColor) from API.lua always use the default values from the mentioned line, not the color selected from the options window. 
A lot of GUI-elements are affected by this - for example the borders of the buttons in the system menu after mouseover.

**Comment by Azilroka** [comment]
Yea, It won't at the moment for Default UI setup.
