### ISSUE TITLE
4.62-12+ causes a fullscreen blackout when browsing Premade Groups

### ISSUE THREAD

**Issue by Taizunz** [Azilroka/AddOnSkins#117]
Reverting to 4.62-11 fixes the issue.
![image](https://user-images.githubusercontent.com/15648000/220398338-44155f03-8d2b-41c9-ad63-b2fbb7de3fff.png)

**Comment by Azilroka** [comment]
You need to be on release 4.68

**Comment by Taizunz** [comment]
There isn't even a 4.63... how do you expect me to be on 4.68?
