### ISSUE TITLE
getting this error just started happening a couple days ago

### ISSUE THREAD

**Issue by lilrussy** [Azilroka/AddOnSkins#124]
Message: ...eumUI/Modules/Skins/Character/CharacterPanelSkin.lua:459: attempt to index field 'DefenseCategory' (a nil value)
Time: Sat Mar 18 13:11:43 2023
Count: 1
Stack: ...eumUI/Modules/Skins/Character/CharacterPanelSkin.lua:459: attempt to index field 'DefenseCategory' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_EltreumUI/Modules/Skins/Character/CharacterPanelSkin.lua"]:459: in function `ExpandedCharacterStats'
[string "@Interface/AddOns/ElvUI_EltreumUI/Init.lua"]:83: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals

**Comment by Repooc** [comment]
this isnt addonskins error, the error line shows EltreumUI
