### ISSUE TITLE
Error of Skada 

### ISSUE THREAD

**Issue by bonus1ife** [Azilroka/AddOnSkins#144]
Hello  -  after updating Addon Skins to 4.63, the following error appeared with Skada 
7x AddOnSkins/Embed/Skada.lua:64: attempt to call method 'EmbedSkadaWindow' (a nil value)
[string "@AddOnSkins/Embed/Skada.lua"]:64: in function Skada'
[string "@AddOnSkins/Core/EmbedSystem.lua"]:139: in function Check'
[string "@AddOnSkins/Core/EmbedSystem.lua"]:82: in function <AddOnSkins/Core/EmbedSystem.lua:82>
Wotlk classic

**Comment by Repooc** [comment]
update to 4.64
