### ISSUE TITLE
Ther was an error in the following skins

### ISSUE THREAD

**Issue by Sprees26** [Azilroka/AddOnSkins#145]
AddOnSkins 4.64: There was an error in the following skin(s): RareScanner 10.1.0.3, QuestCompletist 109.44

![wow](https://user-images.githubusercontent.com/132806193/236661933-66227292-a56a-4aaa-95da-1ac72e0031ef.jpg)

**Comment by nihilistzsche** [comment]
https://github.com/Azilroka/AddOnSkins/commit/b4fed9b6648675a7c9502611d9ed9f91e5dcbfcf
