### ISSUE TITLE
WOTLK - Guild Roster Manager FontScaleSlider lua errors in version 4.63 and later.

### ISSUE THREAD

**Issue by rdobkins** [Azilroka/AddOnSkins#148]
AS:SkinSlideBar(GRM_FontSizeSlider) is returning a nil value for anchorpoint when attempting to relocate the position of the FontString and throwing lua errors.  If you disable all calls to this, the skin will load.

**Comment by nihilistzsche** [comment]
https://github.com/Azilroka/AddOnSkins/commit/5336c3d7ab6e32a695c2939e4296a4308d0e2621
