### ISSUE TITLE
AllTheThings settings window wrapping issue

### ISSUE THREAD

**Issue by ninaarens** [Azilroka/AddOnSkins#15]
Hello, I'm a contributor on ATT and I'd like to report an issue with addonskins that affects our settings screen.

Since 9.1, we've had wrapping issues with the checkboxes on the ATT settings screen as Blizzard changed them to all be default 250px wide. We've found a fix for this by setting the width of the text belonging to the checkbox to the unbounded width of the text string that goes into it. See the code sample below.

```
local cb = CreateFrame("CheckButton", self:GetName() .. "-" .. text, self, "InterfaceOptionsCheckButtonTemplate");
cb.Text:SetText(text);
local textWidth = math.ceil(cb.Text:GetUnboundedStringWidth());
cb.Text:SetWidth(textWidth);
```

However, when a user has addonskins apply a skin to ATT, we end up with the wrapping issue returning, as seen below. The only way to remedy this is to add additional width to the textWidth local. But obviously we'd rather not do this on our end, as for users who only use our addon, there is no problem after we introduced our fix.

![image](https://user-images.githubusercontent.com/8618272/134413112-8e5508b0-a85f-4eed-a2f8-8690c85a6a68.png)

We were wondering if you could look if there is anything on your end that is doing this to the settings frame? As far as I can tell, nothing is actually being skinned on there? If there is, and I'm not seeing it because ElvUI already takes care of it, could you investigate what is causing the settings checkbox text to wrap when addonskins applies itself?

**Comment by Azilroka** [comment]
Is that an ace3 window? If so.. You may want to see if it's the Ace3 skin doing it and that would most likely be in ElvUI - Skins.. The only thing I touch is the windows themselves.. I hardly ever touch the options windows.

**Comment by Azilroka** [comment]
I can't seem to find the root cause.. I do know Ace is affecting it.. I did have to add AllTheThings to my toc to get it to load correctly.. So I'll have to dig a little deeper.
