### ISSUE TITLE
Skin disabled on reload

### ISSUE THREAD

**Issue by Nilsen02** [Azilroka/AddOnSkins#155]
Hi there!

I've made a skin for RXP Guides to make it look more like ElvUI and I got the skin itself working, retexturing the addon, however after a /reload the skin was disabled, and every time I now enable it and then reload to redo the textures, the skin is disabled again.
Any idea to what could be the culprit/what kinda logs I could supply you guys with?

**Comment by Azilroka** [comment]
You need to turn on Skin Debug to stop it from disabling the skin through errors. It will also throw the errors for you to diagnose the issue.
