### ISSUE TITLE
transparent backdrop on tool tips

### ISSUE THREAD

**Issue by nazrion** [Azilroka/AddOnSkins#174]
I don't get any LUA errors but transparent backdrops on most of the game minimap tooltips when AddOnSkins is enabled.

See attached image for reference.
![transbackdrop](https://github.com/Azilroka/AddOnSkins/assets/54301453/8f8bf707-e528-4510-9226-9ad43da297db)

**Comment by Coopeke** [comment]
I was able to narrow this down to the "Libraries" skin.  I disabled this in the addon options for Addonskins on the Skins tab and all my minimap buttons tooltips had backdrops again after reload.

Hope this helps.
