### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by ToxxicApe** [Azilroka/AddOnSkins#189]
LUA Error 1

1x AddOnSkins/Core/Skins.lua:1654: attempt to index local 'frame' (a nil value)
[string "@AddOnSkins/Core/Skins.lua"]:1654: in function `Desaturate'
[string "@AddOnSkins/SkinsMinimalArchaeology.lua"]:10: in function <...ddOns/AddOnSkins/SkinsMinimalArchaeology.lua:3>
[string "@AddOnSkins/Core/Core.lua"]:182: in function <AddOnSkins/Core/Core.lua:182>
[string "=[C]"]: in function `xpcall'
[string "@AddOnSkins/Core/Core.lua"]:182: in function `CallSkin'
[string "@AddOnSkins/Core/Core.lua"]:123: in function `SkinEvent'
[string "@AddOnSkins/Core/Core.lua"]:263: in function `?'
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 HandleCollapseTexture = <function> defined @AddOnSkins/Core/Skins.lua:2132
 Point = <function> defined @AddOnSkins/Core/Skins.lua:212
 HandleFrame = <function> defined @AddOnSkins/Core/Skins.lua:580
 ArrowRotation = <table> {
 }
 HandleNextPrevButton = <function> defined @AddOnSkins/Core/Skins.lua:1511
 modules = <table> {
 }
 ToggleBorders = <function> defined @AddOnSkins/Core/Skins.lua:267
 SecureHook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:335
 HandleIcon = <function> defined @AddOnSkins/Core/Skins.lua:1445
 GetTemplate = <function> defined @AddOnSkins/Core/Skins.lua:260
 SetDefaultModulePrototype = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 SetDisabledBackdrop = <function> defined @AddOnSkins/Core/Skins.lua:677
 HandleCategoriesButtons = <function> defined @AddOnSkins/Core/Skins.lua:516
 IsEnabled = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 SkinStackedResourceTrackerWidget = <function> defined @AddOnSkins/Core/Skins.lua:2200
 SetTemplate = <function> defined @AddOnSkins/Core/Skins.lua:275
 SkinLibDropDownMenu = <function> defined @AddOnSkins/Core/Skins.lua:787
 WatchPixelSnap = <function> defined @AddOnSkins/Core/Skins.lua:159
 RegisterMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 SkinTalentListButtons = <function> defined @AddOnSkins/Core/Skins.lua:811
 hooks = <table> {
 }
 HandleEditBox = <function> defined @AddOnSkins/Core/Skins.lua:1268
 UIScale = 0.710000
 Size = <function> defined @AddOnSkins/Core/Skins.lua:199
 SetEnabledState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:273
 HandlePortraitFrame = <function> defined @AddOnSkins/Core/Skins.lua:627
 SetPointsRestricted = <function> defined @AddOnSkins/Core/Skins.lua:147
 SkinTextWithStateWidget = <function> defined @AddOnSkins/Core/Skins.lua:2206
 FollowerListUpdateDataFrames = <table> {
 }
 SkinDoubleStateIconRow = <function> defined @AddOnSkins/Core/Skins.lua:2242
 HandleTrimScrollBar = <function> defined @AddOnSkins/Core/Skins.lua:1117
 SkinWidgetContainer = <function> defined @AddOnSkins/Core/Skins.lua:2281
 Media = <table> {
 }
 PVPHonorXPBarFrames = <table> {
 }
 NewModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 SafeGetPoint = <function> defined @AddOnSkins/Core/Skins.lua:153
 Templates = <table> {
 }
 SkinBulletTextListWidget = <function> defined @AddOnSkins/Core/Skins.lua:2216
 EnumObjects = <function> defined @AddOnSkins/Core/Skins.lua:1710
 HandleMaxMinFrame = <function> defined @AddOnSkins/Core/Skins.lua:1223
 Hider = Frame {
 }
 CleanTexture = <function> defined @AddOnSkins/Core/Skins.lua:1625
 SkinCaptureZone = <function> defined @AddOnSkins/Core/Skins.lua:2251
 GetName = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "AddOnSkins_Skins"
 Disable = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
 Kill = <function> defined @AddOnSkins/Core/Skins.lua:120
 Unhook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:417
 Shadows = <table> {
 }
 StatusBars = <table> {
 }
 SkinDoubleStatusBarWidget = <function> defined @AddOnSkins/Core/Skins.lua:2188
 HandleButton = <function> defined @AddOnSkins/Core/Skins.lua:925
 moduleName = 
 
 
 
 
 LUA Error 2

1x AddOnSkins/Core/Skins.lua:926: attempt to index local 'button' (a nil value)
[string "@AddOnSkins/Core/Skins.lua"]:926: in function `HandleButton'
[string "@AddOnSkins/SkinsColorPickerPlus.lua"]:24: in function <...eAddOnSkins/SkinsColorPickerPlus.lua:3>
[string "@AddOnSkins/Core/Core.lua"]:182: in function <AddOnSkins/Core/Core.lua:182>
[string "=[C]"]: in function `xpcall'
[string "@AddOnSkins/Core/Core.lua"]:182: in function `CallSkin'
[string "@AddOnSkins/Core/Core.lua"]:123: in function `SkinEvent'
[string "@AddOnSkins/Core/Core.lua"]:263: in function `?'
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 HandleCollapseTexture = <function> defined @AddOnSkins/Core/Skins.lua:2132
 Point = <function> defined @AddOnSkins/Core/Skins.lua:212
 HandleFrame = <function> defined @AddOnSkins/Core/Skins.lua:580
 ArrowRotation = <table> {
 }
 HandleNextPrevButton = <function> defined @AddOnSkins/Core/Skins.lua:1511
 modules = <table> {
 }
 ToggleBorders = <function> defined @AddOnSkins/Core/Skins.lua:267
 SecureHook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:335
 HandleIcon = <function> defined @AddOnSkins/Core/Skins.lua:1445
 GetTemplate = <function> defined @AddOnSkins/Core/Skins.lua:260
 SetDefaultModulePrototype = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 SetDisabledBackdrop = <function> defined @AddOnSkins/Core/Skins.lua:677
 HandleCategoriesButtons = <function> defined @AddOnSkins/Core/Skins.lua:516
 IsEnabled = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 SkinStackedResourceTrackerWidget = <function> defined @AddOnSkins/Core/Skins.lua:2200
 SetTemplate = <function> defined @AddOnSkins/Core/Skins.lua:275
 SkinLibDropDownMenu = <function> defined @AddOnSkins/Core/Skins.lua:787
 WatchPixelSnap = <function> defined @AddOnSkins/Core/Skins.lua:159
 RegisterMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 SkinTalentListButtons = <function> defined @AddOnSkins/Core/Skins.lua:811
 hooks = <table> {
 }
 HandleEditBox = <function> defined @AddOnSkins/Core/Skins.lua:1268
 UIScale = 0.710000
 Size = <function> defined @AddOnSkins/Core/Skins.lua:199
 SetEnabledState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:273
 HandlePortraitFrame = <function> defined @AddOnSkins/Core/Skins.lua:627
 SetPointsRestricted = <function> defined @AddOnSkins/Core/Skins.lua:147
 SkinTextWithStateWidget = <function> defined @AddOnSkins/Core/Skins.lua:2206
 FollowerListUpdateDataFrames = <table> {
 }
 SkinDoubleStateIconRow = <function> defined @AddOnSkins/Core/Skins.lua:2242
 HandleTrimScrollBar = <function> defined @AddOnSkins/Core/Skins.lua:1117
 SkinWidgetContainer = <function> defined @AddOnSkins/Core/Skins.lua:2281
 Media = <table> {
 }
 PVPHonorXPBarFrames = <table> {
 }
 NewModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 SafeGetPoint = <function> defined @AddOnSkins/Core/Skins.lua:153
 Templates = <table> {
 }
 SkinBulletTextListWidget = <function> defined @AddOnSkins/Core/Skins.lua:2216
 EnumObjects = <function> defined @AddOnSkins/Core/Skins.lua:1710
 HandleMaxMinFrame = <function> defined @AddOnSkins/Core/Skins.lua:1223
 Hider = Frame {
 }
 CleanTexture = <function> defined @AddOnSkins/Core/Skins.lua:1625
 SkinCaptureZone = <function> defined @AddOnSkins/Core/Skins.lua:2251
 GetName = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 name = "AddOnSkins_Skins"
 Disable = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
 Kill = <function> defined @AddOnSkins/Core/Skins.lua:120
 Unhook = <function> defined @Ace3/AceHook-3.0/AceHook-3.0.lua:417
 Shadows = <table> {
 }
 StatusBars = <table> {
 }
 SkinDoubleStatusBarWidget = <function> defined @AddOnSkins/Core/Skins.lua:2188
 HandleButton = <function> defined @AddOnSkins/Core/Skins.lua:925
 moduleName =

**Comment by DevTyldor** [comment]
Bump, I got this issue too with cora.lua.

![image](https://github.com/user-attachments/assets/36f103fa-bc2f-466f-8696-277c1c3a6ae2)
