### ISSUE TITLE
BigWigs packager not being used correctly

### ISSUE THREAD

**Issue by jmsundar** [Azilroka/AddOnSkins#201]
According to the WoW Packager action [docs/readme](https://github.com/marketplace/actions/wow-packager), the repository should be tagged with version number:
>release.sh assumes that tags (Git annotated tags and SVN tags) are named for the version numbers for the project. It will identify if the HEAD is tagged and use that as the current version number. It will search back through parent commits for the previous tag and generate a changelog containing the commits since that tag.

Since the release workflow in this repository isn't incrementing the version tag, the files at Curse/wago are being updated under the same version number. This doesn't have a huge impact, but does make it harder to update the addon and leads to an incorrect "released at" date from both addon managers.

Fix:
update the workflow to also autoincrement the tag.
https://github.com/Azilroka/AddOnSkins/blob/main/.github/workflows/release.yml

**Comment by Azilroka** [comment]
Are you sure it's not being used correctly?

Here is the annotated tags.

https://github.com/Azilroka/AddOnSkins/tags

I can make it do it automatically, yes. However I haven't actually pushed a new release as of yet.

**Comment by jmsundar** [comment]
It looks to me like a release is being pushed to the addon hosts with every PR merge. The "updated at" on wago is today. 

wago:
https://addons.wago.io/addons/RXKqy5Ky

release on every PR:
https://github.com/Azilroka/AddOnSkins/actions/workflows/release.yml

sample log from release workflow showing package being uploaded:
```
Creating archive: AddOnSkins-4.68-9-gd0fe076.zip (4.68-9-gd0fe076)
Uploading AddOnSkins-4.68-9-gd0fe076.zip (10.1.0,3.4.1,1.14.4 alpha) to https://www.curseforge.com/projects/54541
Success!

Uploading AddOnSkins-4.68-9-gd0fe076.zip (10.1.0,3.4.1,1.14.4 alpha) to https://addons.wago.io/addons/RXKqy5Ky
Success!
```

**Comment by jmsundar** [comment]
So even though you're not "pushing" a new release with a new tag, there's releases going to the hosts with a previous version number.

**Comment by Azilroka** [comment]
Exactly. Those are alpha releases not a full release.  So in twitch and curse there is an alpha version selection (also beta) which is the way I am running it. The way you suggesting to run it is that anytime there is a commit it would increase the versioning number which means I would need to follow the wow versioning number with a subset of numbers eg: 11.0.0.12345 11.0.0.12346 etc

**Comment by jmsundar** [comment]
Oh, I didn't see the alpha releases. My bad
