### ISSUE TITLE
Changes to API: IsAddOnLoaded → C_AddOns.IsAddOnLoaded

### ISSUE THREAD

**Issue by masomh-personal** [Azilroka/AddOnSkins#207]
https://github.com/Azilroka/AddOnSkins/blob/b29ed77b4c942fd47dc7fcd19aeb66d38d2c9b20/AddOnSkins/Core/Core.lua#L14

REFERENCE: https://warcraft.wiki.gg/wiki/API_C_AddOns.IsAddOnLoaded

`local IsAddOnLoaded, C_Timer = IsAddOnLoaded, C_Timer` 

to 

`local IsAddOnLoaded, C_Timer = C_AddOns.IsAddOnLoaded, C_Timer`

**Comment by Tempost** [comment]
Made change locally and addon is working now 👍

**Comment by masomh-personal** [comment]
> Made change locally and addon is working now 👍

I wish all bugs were that easy to fix lol.
