### ISSUE TITLE
Lua on Login Core.lua280

### ISSUE THREAD

**Issue by Sharios999** [Azilroka/AddOnSkins#213]
14x AddOnSkins/Core/Core.lua:280: attempt to call upvalue 'IsAddOnLoaded' (a nil value)
[string "@AddOnSkins/Core/Core.lua"]:280: in function `?'
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 FrameLocks = <table> {
 }
 modules = <table> {
 }
 Skins = <table> {
 }
 SkinErrors = <table> {
 }
 hooks = <table> {
 }
 Version = 4.680000
 EmbedSystem = <table> {
 }
 name = "AddOnSkins"
 preload = <table> {
 }
 skins = <table> {
 }
 MyName = "Sharipriest"
 MyRealm = "Blackhand"
 defaultModuleState = true
 Authors = "Azilroka    Nihilistzsche"
 ProperVersion = "4.68"
 enabledState = true
 Wrath = false
 Retail = true
 baseName = "AddOnSkins"
 Options = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 AddOnVersion = <table> {
 }
 TexCoords = <table> {
 }
 AddOns = <table> {
 }
 Faction = "Alliance"
 Libs = <table> {
 }
 orderedModules = <table> {
 }
 Classic = false
 Title = "|cff16C3F2AddOn|r|cFFFFFFFFSkins|r"
 MyClass = "PRIEST"
 TicketTracker = "https://github.com/Azilroka/AddOnSkins/issues"
 events = <table> {
 }
 TBC = false
}
event = "ADDON_LOADED"
addon = "AddOnSkins"
(*temporary) = nil
(*temporary) = "AddOnSkins"
(*temporary) = "attempt to call upvalue 'IsAddOnLoaded' (a nil value)"
AS = <table> {
 FrameLocks = <table> {
 }
 modules = <table> {
 }
 Skins = <table> {
 }
 SkinErrors = <table> {
 }
 hooks = <table> {
 }
 Version = 4.680000
 EmbedSystem = <table> {
 }
 name = "AddOnSkins"
 preload = <table> {
 }
 skins = <table> {
 }
 MyName = "Sharipriest"
 MyRealm = "Blackhand"
 defaultModuleState = true
 Authors = "Azilroka    Nihilistzsche"
 ProperVersion = "4.68"
 enabledState = true
 Wrath = false
 Retail = true
 baseName = "AddOnSkins"
 Options = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 AddOnVersion = <table> {
 }
 TexCoords = <table> {
 }
 AddOns = <table> {
 }
 Faction = "Alliance"
 Libs = <table> {
 }
 orderedModules = <table> {
 }
 Classic = false
 Title = "|cff16C3F2AddOn|r|cFFFFFFFFSkins|r"
 MyClass = "PRIEST"
 TicketTracker = "https://github.com/Azilroka/AddOnSkins/issues"
 events = <table> {
 }
 TBC = false
}
IsAddOnLoaded = nil
AddOnName = "AddOnSkins"

**Comment by Sintry1** [comment]
[12:42:28] 222x AddOnSkins/Core/Core.lua:266: attempt to call upvalue 'IsAddOnLoaded' (a nil value)
[string "@AddOnSkins/Core/Core.lua"]:266: in function `?'
[string "@SharedMedia/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...dia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@SharedMedia/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...dia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@SharedMedia/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 FrameLocks = <table> {
 }
 modules = <table> {
 }
 Skins = <table> {
 }
 SkinErrors = <table> {
 }
 hooks = <table> {
 }
 Version = 4.710000
 EmbedSystem = <table> {
 }
 name = "AddOnSkins"
 preload = <table> {
 }
 skins = <table> {
 }
 MyName = "Sintvoker"
 MyRealm = "Argent Dawn"
 defaultModuleState = true
 Authors = "Azilroka    Nihilistzsche"
 ProperVersion = "4.71"
 enabledState = true
 Title = "|cff16C3F2AddOn|r|cFFFFFFFFSkins|r"
 baseName = "AddOnSkins"
 Options = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 AddOnVersion = <table> {
 }
 TicketTracker = "https://github.com/Azilroka/AddOnSkins/issues"
 AddOns = <table> {
 }
 Libs = <table> {
 }
 orderedModules = <table> {
 }
 Hider = Frame {
 }
 Classic = false
 TexCoords = <table> {
 }
 MyClass = "EVOKER"
 Wrath = false
 Retail = true
 Faction = "Alliance"
 events = <table> {
 }
 TBC = false
}
event = "ADDON_LOADED"
addon = "AddOnSkins"
(*temporary) = nil
(*temporary) = "AddOnSkins"
(*temporary) = "attempt to call upvalue 'IsAddOnLoaded' (a nil value)"
AS = <table> {
 FrameLocks = <table> {
 }
 modules = <table> {
 }
 Skins = <table> {
 }
 SkinErrors = <table> {
 }
 hooks = <table> {
 }
 Version = 4.710000
 EmbedSystem = <table> {
 }
 name = "AddOnSkins"
 preload = <table> {
 }
 skins = <table> {
 }
 MyName = "Sintvoker"
 MyRealm = "Argent Dawn"
 defaultModuleState = true
 Authors = "Azilroka    Nihilistzsche"
 ProperVersion = "4.71"
 enabledState = true
 Title = "|cff16C3F2AddOn|r|cFFFFFFFFSkins|r"
 baseName = "AddOnSkins"
 Options = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 AddOnVersion = <table> {
 }
 TicketTracker = "https://github.com/Azilroka/AddOnSkins/issues"
 AddOns = <table> {
 }
 Libs = <table> {
 }
 orderedModules = <table> {
 }
 Hider = Frame {
 }
 Classic = false
 TexCoords = <table> {
 }
 MyClass = "EVOKER"
 Wrath = false
 Retail = true
 Faction = "Alliance"
 events = <table> {
 }
 TBC = false
}
IsAddOnLoaded = nil
AddOnName = "AddOnSkins"

Also getting the same error
