### ISSUE TITLE
DejaCharacterStats / DejaClassicStats Skin not working?

### ISSUE THREAD

**Issue by goldenpipes** [Azilroka/AddOnSkins#225]
Title

**Comment by Azilroka** [comment]
Response

**Comment by goldenpipes** [comment]
lol thanks for the response,  I never really looked in to LUA or addon coding much, nbd if it doesn't work just wanted to see.

love your work! thank you for all the skins!

**Comment by goldenpipes** [comment]
duplicate of https://github.com/Azilroka/AddOnSkins/issues/190
