### ISSUE TITLE
AddOnSkins + Dominos

### ISSUE THREAD

**Issue by maQZ89** [Azilroka/AddOnSkins#23]
I isolated this Problem to AddonSkins and Domins. 
I downloaded both Addon freshly and didnt load any profiles. 
I tryed to fix Dominos settings, but couldn't find any solution. 
From my understanding it's a Problem with AddOnSkins. 
The FullwindowCooldown is shown as long as the actionbar is visible from dominos. 
e.g. if i the action bar is on faded opacity the cooldown just shows when i hover over the bar. 

A fix would be super nice! 
![Dominos+Addonskins](https://user-images.githubusercontent.com/94395393/141833562-55db790c-3351-4ca1-ba26-434afdc58128.jpg)

**Comment by Azilroka** [comment]
I checked this and it is working for me.. So maybe you are out of date on AddOnSkins. I haven't touched anything either for Dominos are awhile.
