### ISSUE TITLE
AddOnSkins\Skins\MainlineRaiderIO-9.1.5

### ISSUE THREAD

**Issue by antedap** [Azilroka/AddOnSkins#25]
155x AddOnSkins\Skins\MainlineRaiderIO-9.1.5 (v202110301908).lua:16: attempt to index field 'RaiderIOProfileTooltip' (a nil value)
[string "@AddOnSkins\Skins\MainlineRaiderIO-9.1.5 (v202110301908).lua"]:16: in function <AddOnSkins\Skins\MainlineRaiderIO.lua:15>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2931: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2776: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2644: in function <FrameXML\UIParent.lua:2640>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3495: in function `ShowUIPanel'
[string "@FrameXML\PVEFrame.lua"]:130: in function `PVEFrame_ShowFrame'
[string "@FrameXML\PVEFrame.lua"]:88: in function <FrameXML\PVEFrame.lua:64>
[string "=[C]"]: in function `PVEFrame_ToggleFrame'
[string "TOGGLEGROUPFINDER"]:1: in function <[string "TOGGLEGROUPFINDER"]:1>

Locals:
self = PVEFrame {
 0 = <userdata>
 TitleText = PVEFrameTitleText {
 }
 portrait = PVEFramePortrait {
 }
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
 MERShadow = true
 SetPortraitShown = <function> defined @SharedXML\PortraitFrame.lua:52
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
 Inset = PVEFrameLeftInset {
 }
 SetPoint = <function> defined =[C]:-1
 SetPortraitTextureRaw = <function> defined @SharedXML\PortraitFrame.lua:40
 shadows = <unnamed> {
 }
 template = "Transparent"
 tab1 = PVEFrameTab1 {
 }
 TitleBg = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:347
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:382
 SetTitleMaxLinesAndHeight = <function> defined @SharedXML\PortraitFrame.lua:68
 SetTitleColor = <function> defined @SharedXML\PortraitFrame.lua:56
 tab3 = PVEFrameTab3 {
 }
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:400
 maxTabWidth = 181.333333
 styling = PVEFrame {
 }
 Center = <unnamed> {
 }
 SetTitle = <function> defined @SharedXML\PortraitFrame.lua:60
 RightEdge = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:319
 shadow = <unnamed> {
 }
 BottomEdge = <unnamed> {
 }
 SetPortraitTexCoord = <function> defined @SharedXML\PortraitFrame.lua:48
 PixelSnapDisabled = true
 SetBorder = <function> defined @SharedXML\PortraitFrame.lua:27
 layoutType = "PortraitFrameTemplate"
 BottomRightCorner = <unnamed> {
 }
 BottomLeftCorner = <unnamed> {
 }
 TopRightCorner = <unnamed> {
 }
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
 SetPortraitAtlasRaw = <function> defined @SharedXML\PortraitFrame.lua:44
 SetPortraitToUnit = <function> defined @SharedXML\PortraitFrame.lua:36
 TopLeftCorner = <unnamed> {
 }
 Bg = PVEFrameBg {
 }
 backdropInfo = <table> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
 SetTitleFormatted = <function> defined @SharedXML\PortraitFrame.lua:64
 NineSlice = <unnamed> {
 }
 TopTileStreaks = <unnamed> {
 }
 TopEdge = <unnamed> {
 }
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:331
 SetPortraitToAsset = <function> defined @SharedXML\PortraitFrame.lua:32
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
 tab2 = PVEFrameTab2 {
 }
 numTabs = 3
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:335
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:462
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:299
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:452
 LeftEdge = <unnamed> {
 }
 CloseButton = PVEFrameCloseButton {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'RaiderIOProfileTooltip' (a nil value)"
_G = <table> {
 0 = 1
 ContainerFrame5Item7 = ContainerFrame5Item7 {
 }
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 746
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 402
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 PawnItemComparer = <function> defined @Pawn\Pawn.lua:3964
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture {
 }
 LFGListInviteDialog_OnEv

**Comment by Azilroka** [comment]
Fixed on git and alpha version of AddOnSkins.
