### ISSUE TITLE
Most recent update did something to Item Rack

### ISSUE THREAD

**Issue by linkx2252** [Azilroka/AddOnSkins#30]
Hi, I just updated and for some reason it reverted/broke the itemrack skin. It seems to have a huge ugly grey border now - before update, it was a sleek no border. 
![Capture](https://user-images.githubusercontent.com/74163581/147843884-fd53cf21-8649-4b17-9c02-c396094111b8.PNG)

**Comment by Azilroka** [comment]
I have to recode the skin.

**Comment by linkx2252** [comment]
Sounds good!!! I have no clue what the means or how difficult it is but I look forward to the update :)
