### ISSUE TITLE
ItemRack skin not working in latest version.

### ISSUE THREAD

**Issue by theycallmek** [Azilroka/AddOnSkins#32]
It looks like ItemRack.lua was removed from "\AddOnSkins\Skins\AddOns\" and the file "\AddOnSkins\Skins\AddOns\Load_Skins.xml" no longer refences ItemRack.lua.

I was able to move the .lua from an older version into the new version AddOns folder and add the reference back into Load_Skins.xml. The skin seems to be working for ItemRack after the few changes I made.

**Comment by plaidshorts** [comment]
This issue still occurs when using ItemRack and AddonSkins 4.58
