### ISSUE TITLE
RCLootCouncil 3.3.0 error

### ISSUE THREAD

**Issue by mdscatharina** [Azilroka/AddOnSkins#48]
I can't use RCLootCouncil skin, and it asked me to report the error so here I am! Weird 'cause it works just fine for a friend of mine :(

**Comment by LiakGamer** [comment]
![image](https://user-images.githubusercontent.com/104516708/165558119-b1e20c09-dff4-4bdd-b695-279b6b591c88.png)
Just adding the error message to that same issue
